version: '3'
services:
    mysql:
        build: ./startup
        command: 
            --default-authentication-plugin=mysql_native_password
            --character-set-server=utf8mb4
            --collation-server=utf8mb4_general_ci
            --plugin-dir=/tmp
            --secure-file-priv=/tmp
        environment:
            MYSQL_RANDOM_ROOT_PASSWORD: yes
            MYSQL_USER: test
            MYSQL_PASSWORD: 123456
            MYSQL_DATABASE: db
            TZ: Asia/Shanghai
        restart: on-failure
        ports:
            - "33062:3306"
