version: '3'
services:
    src:
        build: ./src/
        volumes:
          - ./src/test.php:/var/www/html/test.php
        tty: true
        ports:
            - "10009:80"
        restart: on-failure
