version: '3'
services:
    src:
        image: 'redis:6.2.10-alpine'
        command: >
          --requirepass '123456'
        tty: true
        ports:
            - "6379:6379"
        restart: on-failure
